// src/lib/components/cv/Contact.svelte
<script lang="ts">
  import { page } from "$app/stores"
  import { cvData } from "$lib/cv/data/CvData"

  import EmailIcon from "virtual:icons/mdi/email"
  import GithubIcon from "virtual:icons/mdi/github"
  import LinkedinIcon from "virtual:icons/mdi/linkedin"
  import PhoneIcon from "virtual:icons/mdi/phone-classic"
  import WebIcon from "virtual:icons/mdi/web"

  $: queries = Object.fromEntries(new URLSearchParams($page.url.search))
</script>

<section>
  <h3 class="cv-h3">{cvData.person.firstName} {cvData.person.lastName}</h3>
  <div class="item">
    <GithubIcon size="20" color="#3d7ad9" />
    <a href="https://github.com/{cvData.person.github}" class="link" target="_blank">
      {cvData.person.github}
    </a>
  </div>
  <div class="item">
    <LinkedinIcon size="20" color="#3d7ad9" />
    <a href="https://www.linkedin.com/in/{cvData.person.linkedin}" class="link" target="_blank">
      {cvData.person.linkedin}
    </a>
  </div>
  <div class="item">
    <WebIcon size="20" color="#3d7ad9" />
    <a href="https://{cvData.person.website}" class="link" target="_blank">
      {cvData.person.website}
    </a>
  </div>
  {#if queries["phone"]}
    <div class="item">
      <PhoneIcon size="20" color="#3d7ad9" />
      <a href="tel:{queries['phone']}" class="link" target="_blank">
        {queries["phone"]}
      </a>
    </div>
  {/if}
  {#if queries["email"]}
    <div class="item">
      <EmailIcon size="20" color="#3d7ad9" />
      <a href="mailto:{queries['email']}" class="link" target="_blank">
        {queries["email"]}
      </a>
    </div>
  {/if}
</section>

<style>
  section {
    display: flex;
    flex-direction: column;
    gap: var(--s2);
  }
  .link {
    color: var(--color1);
    text-decoration: none;
  }
  .item {
    display: flex;
    flex-direction: row;
    align-items: center;
    gap: var(--s2);
  }
</style>

// src/cv/Contact.tsx
import React from "react"
import {
  AiOutlineMail,
  AiOutlinePhone,
  AiOutlineTwitter,
  AiFillLinkedin,
  AiFillGithub,
  AiOutlineGlobal
} from "react-icons/ai"
import { StyleSheet, css, CSSProperties } from "aphrodite/no-important"
import { useMesages } from "../intl/useIntl"
import { SectionTitle } from "./SectionTitle"
import { Person } from "./models"

interface Props {
  person: Person
  phone?: string
}

export function Contact({ phone, person: { firstName, lastName, email, twitter, linkedin, github, website } }: Props) {
  const message = useMesages()

  return (
    <section className={css(styles.contact)}>
      <SectionTitle title={message("contactTitle")} />
      <div className={css(styles.item)}>
        <h2 className={css(styles.name)}>{`${firstName} ${lastName}`}</h2>
      </div>
      <div className={css(styles.item)}>
        <AiOutlineMail size="20" color="#3d7ad9" />
        <a href={`mailto:${email}`} className={css(styles.itemLink)}>
          {email}
        </a>
      </div>
      {github ? (
        <div className={css(styles.item)}>
          <AiOutlineGlobal size="20" color="#3d7ad9" />
          <a href={`https://${website}`} className={css(styles.itemLink)}>
            {website}
          </a>
        </div>
      ) : undefined}
      {github ? (
        <div className={css(styles.item)}>
          <AiFillGithub size="20" color="#3d7ad9" />
          <a href={`https://github.com/${github}`} className={css(styles.itemLink)}>
            {github}
          </a>
        </div>
      ) : undefined}
      {linkedin ? (
        <div className={css(styles.item)}>
          <AiFillLinkedin size="20" color="#3d7ad9" />
          <a href={`https://www.linkedin.com/in/${linkedin}`} className={css(styles.itemLink)}>
            {linkedin}
          </a>
        </div>
      ) : undefined}
      {twitter ? (
        <div className={css(styles.item)}>
          <AiOutlineTwitter size="20" color="#3d7ad9" />
          <a href={`https://twitter.com/${twitter}`} className={css(styles.itemLink)}>
            {twitter}
          </a>
        </div>
      ) : undefined}
      {phone ? (
        <div className={css(styles.item)}>
          <AiOutlinePhone size="20" color="#3d7ad9" />
          <a href={`tel:${phone}`} className={css(styles.itemLink)}>
            {phone}
          </a>
        </div>
      ) : undefined}
    </section>
  )
}

const styles = StyleSheet.create<Record<string, CSSProperties>>({
  contact: {
    marginBottom: 20
  },
  itemLink: {
    marginLeft: 5,
    color: "#3d7ad9",
    textDecoration: "none"
  },
  item: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10
  },
  name: {
    fontSize: "1.1rem",
    fontWeight: "bold"
  }
})
